# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 19 Aug 2023 11:39:49 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

test:$2y$10$zzEKUDQMILySmD3bumcZBeL0BuCUOABoTTpw8TF8Sh84rmW7V0FBq:test:test@dummy.org:admin,user
